export { txClient as cosmTxClient, queryClient as cosmQueryClient } from '@/protos/cosmwasm'
export { txClient as dsigTxClient, queryClient as dsigQueryClient } from '@/protos/dsig'
export { txClient as filetreeTxClient, queryClient as filetreeQueryClient } from '@/protos/filetree'
export { txClient as govTxClient, queryClient as govQueryClient } from '@/protos/governance'
export { txClient as jklAccountsTxClient, queryClient as jklAccountsQueryClient } from '@/protos/jklaccounts'
export { txClient as jklMintTxClient, queryClient as jklMintQueryClient } from '@/protos/jklmint'
export { txClient as rnsTxClient, queryClient as rnsQueryClient } from '@/protos/rns'
export { txClient as storageTxClient, queryClient as storageQueryClient } from '@/protos/storage'
